adds readability to the code
MikoreVikt/nodejs-homework-rest-api pull request #3
Opened 2023-03-07 20:06 UTC by MikoreVikt

Трохи відкоригував код))

2023-03-08 10:04 UTC, KhYulian requested changes
Потрібні правки

2023-03-08 10:04 UTC, KhYulian commented on middlewares/validationMiddleware.js
> +    });
Схеми joi також слід винести в окремий файл

2023-03-08 10:04 UTC, KhYulian commented on middlewares/validationMiddleware.js
> +};
Загалом це не дуже хороша практика прописувати функції безпосередньо в module.exports

2023-03-08 10:04 UTC, KhYulian commented on middlewares/validationMiddleware.js
> +};
postValidation та putValidation практично ідентичні. Можна написати більш універсальну функцію, яка прийматиме схему joi та повертатиме middleware, що валідуватиме

2023-03-09 13:47 UTC, MikoreVikt commented
Что-то типа такого?)

2023-03-09 14:33 UTC, KhYulian commented on middlewares/validation/validationMiddleware.js
> +};
```suggestion
const validation = (schema) => {
  return (req, res, next) => {
    const { error } = schema.validate(req.body);

    if (error) {
      return next(error);
    }

    next();
  };
};
```

2023-03-09 14:33 UTC, KhYulian commented on middlewares/validation/validationMiddleware.js
> +};
Можна ще оптимізувати

2023-03-09 14:34 UTC, KhYulian commented on controllers/contactsController.js
> +const getContactByIdController = async (req, res, next) => {
getContactController

2023-03-09 14:34 UTC, KhYulian commented on controllers/contactsController.js
> +const postNewContactController = async (req, res, next) => {
post/createContactController

2023-03-09 14:34 UTC, KhYulian commented on controllers/contactsController.js
> +const putContactController = async (req, res, next) => {
updateContactController

2023-03-09 14:35 UTC, KhYulian approved these changes
Потрібне доопрацювання

2023-03-09 15:56 UTC, MikoreVikt commented
Воно?)

2023-03-10 07:32 UTC, merged

2023-03-10 07:32 UTC, KhYulian commented
👍